# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 555163a521b0cc458aee5932f53db10e838c7af167a7fe89f077214dc5919dd5485b4e6572b72ee6906ea38b86a804be3048eea759464a697a75d89fe4043138

test:
  secret_key_base: d2a0eb0d2ba453a821c0749b455d71dd1ca9c597975df0ba231c7e767c21aae4fbead886dde8bd193fba18551a89cb2ef59b5db2fae17531cbc46bc685dd93cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
